# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build-job:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . env/bin/activate
            python setup.py develop
            python setup.py test
      - run:
          name: build package
          command: |
            . env/bin/activate
            python setup.py sdist

  deploy-job:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - run: 
          name: familiarize with host
          command: |
            ssh-keyscan coursefinder.life >> ~/.ssh/known_hosts
      - run:
          name: deploy package
          command: >-
            scp -v -o ConnectTimeout=10 -o StrictHostKeyChecking=no 
            dist/coursefinder-0.0.tar.gz
            root@coursefinder.life:/root/
      - run:
          name: install and start server
          command: |
            cat unpack_install_start.sh | ssh root@coursefinder.life


workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master

          